# Generated by Django 6.0.4 on 2026-05-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='end_at',
            new_name='finished_at',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='assigned_score',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='score_assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado'), ('EXPIRED', 'Expirado')], default='IN_PROGRESS', max_length=20),
        ),
    ]
